/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated.users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated.projects'
import { Route as AuthenticatedOrganizationsRouteImport } from './routes/_authenticated.organizations'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedIssuesIndexRouteImport } from './routes/_authenticated.issues.index'
import { Route as AuthenticatedIssuesNewRouteImport } from './routes/_authenticated.issues.new'
import { Route as AuthenticatedIssuesIdRouteImport } from './routes/_authenticated.issues.$id'
import { Route as AuthenticatedIssuesIdEditRouteImport } from './routes/_authenticated.issues.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationsRoute =
  AuthenticatedOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIssuesIndexRoute =
  AuthenticatedIssuesIndexRouteImport.update({
    id: '/issues/',
    path: '/issues/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIssuesNewRoute = AuthenticatedIssuesNewRouteImport.update({
  id: '/issues/new',
  path: '/issues/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIssuesIdRoute = AuthenticatedIssuesIdRouteImport.update({
  id: '/issues/$id',
  path: '/issues/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIssuesIdEditRoute =
  AuthenticatedIssuesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedIssuesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/issues/$id': typeof AuthenticatedIssuesIdRouteWithChildren
  '/issues/new': typeof AuthenticatedIssuesNewRoute
  '/issues/': typeof AuthenticatedIssuesIndexRoute
  '/issues/$id/edit': typeof AuthenticatedIssuesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/organizations': typeof AuthenticatedOrganizationsRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/issues/$id': typeof AuthenticatedIssuesIdRouteWithChildren
  '/issues/new': typeof AuthenticatedIssuesNewRoute
  '/issues': typeof AuthenticatedIssuesIndexRoute
  '/issues/$id/edit': typeof AuthenticatedIssuesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/organizations': typeof AuthenticatedOrganizationsRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/issues/$id': typeof AuthenticatedIssuesIdRouteWithChildren
  '/_authenticated/issues/new': typeof AuthenticatedIssuesNewRoute
  '/_authenticated/issues/': typeof AuthenticatedIssuesIndexRoute
  '/_authenticated/issues/$id/edit': typeof AuthenticatedIssuesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/organizations'
    | '/projects'
    | '/settings'
    | '/users'
    | '/issues/$id'
    | '/issues/new'
    | '/issues/'
    | '/issues/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/organizations'
    | '/projects'
    | '/settings'
    | '/users'
    | '/issues/$id'
    | '/issues/new'
    | '/issues'
    | '/issues/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/organizations'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/issues/$id'
    | '/_authenticated/issues/new'
    | '/_authenticated/issues/'
    | '/_authenticated/issues/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations': {
      id: '/_authenticated/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof AuthenticatedOrganizationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/issues/': {
      id: '/_authenticated/issues/'
      path: '/issues'
      fullPath: '/issues/'
      preLoaderRoute: typeof AuthenticatedIssuesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/issues/new': {
      id: '/_authenticated/issues/new'
      path: '/issues/new'
      fullPath: '/issues/new'
      preLoaderRoute: typeof AuthenticatedIssuesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/issues/$id': {
      id: '/_authenticated/issues/$id'
      path: '/issues/$id'
      fullPath: '/issues/$id'
      preLoaderRoute: typeof AuthenticatedIssuesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/issues/$id/edit': {
      id: '/_authenticated/issues/$id/edit'
      path: '/edit'
      fullPath: '/issues/$id/edit'
      preLoaderRoute: typeof AuthenticatedIssuesIdEditRouteImport
      parentRoute: typeof AuthenticatedIssuesIdRoute
    }
  }
}

interface AuthenticatedIssuesIdRouteChildren {
  AuthenticatedIssuesIdEditRoute: typeof AuthenticatedIssuesIdEditRoute
}

const AuthenticatedIssuesIdRouteChildren: AuthenticatedIssuesIdRouteChildren = {
  AuthenticatedIssuesIdEditRoute: AuthenticatedIssuesIdEditRoute,
}

const AuthenticatedIssuesIdRouteWithChildren =
  AuthenticatedIssuesIdRoute._addFileChildren(
    AuthenticatedIssuesIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrganizationsRoute: typeof AuthenticatedOrganizationsRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedIssuesIdRoute: typeof AuthenticatedIssuesIdRouteWithChildren
  AuthenticatedIssuesNewRoute: typeof AuthenticatedIssuesNewRoute
  AuthenticatedIssuesIndexRoute: typeof AuthenticatedIssuesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrganizationsRoute: AuthenticatedOrganizationsRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedIssuesIdRoute: AuthenticatedIssuesIdRouteWithChildren,
  AuthenticatedIssuesNewRoute: AuthenticatedIssuesNewRoute,
  AuthenticatedIssuesIndexRoute: AuthenticatedIssuesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
